create TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) NOT NULL,
	email varchar(254) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT users_email_unique UNIQUE (email)
);

create TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id),
    CONSTRAINT categories_unique UNIQUE (name)
);