#file: noinspection SpringYamlInspection
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
    routes:
      - id: stat-server_circuitbreaker_route
        uri: lb://stat-server
        predicates:
          - Path=/stats
          - Path=/hit
#        filters:
#          - CircuitBreaker=myCircuitBreaker
      - id: main-service_circuitbreaker_route
        uri: lb://main-service
        predicates:
          - Path=/**
        filters:
          - name: Retry
            args:
              retries: 3
              exceptions: ProductNotFoundException
              backoff:
                first-backoff: 10ms
                max-backoff: 50ms
                factor: 2
                based-on-previous-value: false
server:
  port: 8080

