services:
  stats-server:
    build:
      context: ./stat/stat-server/Dockerfile
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
#    depends_on:
#      - stats-db  # Зависимость от базы данных
#
#  stats-db:
#    image: postgres:16.1

  ewm-service:
    build:
      context: ./main-service/Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

#  ewm-db:
#    image: postgres:16.1
